version: "3.9"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build:
      context: ..
      dockerfile: messaging_app/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../:/chats
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      - db

volumes:
  db_data:
