pipeline {
    agent {
        docker {
            image 'python:3.10-slim'
            args '-u root:root'  // ensures permission to write in workspace 
        }
    }

    environment {
        VENV_DIR = "env"
        IMAGE_NAME = "messaging-app"
        IMAGE_TAG  = "latest"
    }

    stages {
        stage('Checkout') {
            git branch: 'main', credentialsId: 'github-credentials', url: 'https://github.com/denisktoo/alx-backend-python.git'
        }

        stage('Setup Python Environment') {
            steps {
                sh 'python -m venv $VENV_DIR'
                sh '. $VENV_DIR/bin/activate && pip3 install --upgrade pip3'
                sh '. $VENV_DIR/bin/activate && pip3 install -r messaging_app/requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                sh '. $VENV_DIR/bin/activate && pytest --junitxml=report.xml'
            }
            post {
                always {
                    junit 'report.xml'
                }
            }
        }

        stage('Build Docker Image') {
            script {
                sh "docker build -t $IMAGE_NAME:$IMAGE_TAG ./messaging_app"
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    withCredentials([usernamePassword(
                        credentialsId: 'dockerhub-credentials',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )]) {
                        sh "echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin"
                        sh "docker push $IMAGE_NAME:$IMAGE_TAG"
                    }
                }
            }
        }
    }
}