#!/usr/bin/env bash
set -euo pipefail

echo "🚀 Starting Minikube..."
minikube start

echo "🔧 Using Minikube Docker daemon..."
eval $(minikube docker-env)

echo "📦 Building Docker image inside Minikube..."
docker build -t messaging-app:1.0 .

echo "ℹ️ Verifying cluster..."
kubectl cluster-info

echo "📦 Listing all pods..."
kubectl get pods -A
