# Generated by Django 5.2.4 on 2025-08-03 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='edited',
            new_name='edited_by',
        ),
    ]
