#!/usr/bin/env bash
set -euo pipefail

kubectl apply -f blue_deployment.yaml
kubectl apply -f messaging_app/green_deployment.yaml
kubectl apply -f kubeservice.yaml

kubectl logs -l app=messaging-app-green
